/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ma.beans.Client;
import ma.beans.Service;
import ma.service.ClientService;
import ma.service.ServiceService;

/**
 *
 * @author Lachgar
 */
public class ClientForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientForm
     */
    ClientService cs;
    ServiceService ss;
    DefaultTableModel model;
    int Id= -1;
    
    public ClientForm() {
        initComponents();
        cs= new ClientService();
        ss= new ServiceService();
        model = (DefaultTableModel) jTableGC.getModel();
        load();
        loadService();
    }
  public void load() {
    model.setRowCount(0); // Assurez-vous que la table est vide avant de la remplir avec de nouvelles données
    for (Client c : cs.findAll()) {
        
        model.addRow(new Object[]{
            c.getId(),
            c.getNom(),
            c.getPrenom(),
            c.getDate(),
            //c.getService()
        });
        
    }
}
  public void loadService(){
      for (Service s : ss.findAll()){
         listeService.addItem(s);
      }
  }


       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomTxt = new javax.swing.JTextField();
        prénomTxt = new javax.swing.JTextField();
        ajouterButton1 = new javax.swing.JButton();
        supprimerButton2 = new javax.swing.JButton();
        modifierButton3 = new javax.swing.JButton();
        listeService = new javax.swing.JComboBox();
        jDateTxt = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableGC = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("gestion des clients");

        jPanel1.setBackground(new java.awt.Color(222, 240, 248));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("formulaire"));

        jLabel1.setText("nom:");

        jLabel2.setText("prénom:");

        ajouterButton1.setText("ajouter");
        ajouterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButton1ActionPerformed(evt);
            }
        });

        supprimerButton2.setText("supprimer");
        supprimerButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerButton2MouseClicked(evt);
            }
        });
        supprimerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerButton2ActionPerformed(evt);
            }
        });

        modifierButton3.setText("modifier");
        modifierButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierButton3ActionPerformed(evt);
            }
        });

        listeService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeServiceActionPerformed(evt);
            }
        });

        jLabel5.setText("service by name:");

        jLabel6.setText("Date:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listeService, 0, 205, Short.MAX_VALUE)
                    .addComponent(prénomTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(nomTxt)
                    .addComponent(jDateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(ajouterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supprimerButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifierButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prénomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ajouterButton1)
                        .addComponent(supprimerButton2)
                        .addComponent(modifierButton3)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("liste des clients"));

        jTableGC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "nom", "prénom", "date", "service"
            }
        ));
        jTableGC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGCMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableGC);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButton1ActionPerformed
        // TODO add your handling code here:
                                                    
    try {
        String nom = nomTxt.getText();
        String prenom = prénomTxt.getText();
       // String dateStr = dateTxt.getText(); // La chaîne de texte de la date
       /*String service = serviceTxt.getText();
        // Convertissez la chaîne de texte du service en un entier
        int serviceId = Integer.parseInt(service);
        // Créez un objet SimpleDateFormat pour analyser la date
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        // Utilisez SimpleDateFormat pour convertir la chaîne de texte en objet Date
        Date date = dateFormat.parse(dateStr);

        // Créez un objet Service (assurez-vous que vous avez une classe Service appropriée)
        // Pour l'instant, supposons que Service ait un constructeur qui prend une chaîne en argument.
        Service serviceObj = new Service(serviceId);

        // Créez un client en utilisant les données récupérées
        Client client = new Client(nom, prenom, date, serviceObj);

        // Ajoutez le client à la base de données ou à votre liste de clients
        if(cs.create(client)){
            JOptionPane.showMessageDialog(this, "ok");
            load();
        }*/
        cs.create(new Client(nom,prenom,jDateTxt.getDate(),(Service)listeService.getSelectedItem()) );
         JOptionPane.showMessageDialog(this, "ok");
        load();
        loadService();
        // Rechargez la table pour refléter les nouvelles données
        //load();
    } catch (Exception e) {
        // Gérez l'erreur de format de date si la chaîne de texte de la date n'est pas valide.
        // Vous pouvez afficher un message d'erreur ou effectuer une autre action appropriée ici.
        e.printStackTrace();
    }


        
    }//GEN-LAST:event_ajouterButton1ActionPerformed
    
    
    private void supprimerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerButton2ActionPerformed
        // TODO add your handling code here:
                                                 
             int reponse =JOptionPane.showConfirmDialog(this, "veullez vous vraiment supprimé ?");
       //JOptionPane.showMessageDialog(this, reponse+" ");
             if(reponse==0){
                 if(cs.delete(cs.findById(Id))){
           //JOptionPane.showMessageDialog(this, Id);//récupération de l'Id 
                 JOptionPane.showMessageDialog(this, "supprimé");
                 load(); //actualiser le tableau
                 loadService();
       }                                      
             }
    }//GEN-LAST:event_supprimerButton2ActionPerformed

    private void supprimerButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerButton2MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_supprimerButton2MouseClicked

    private void jTableGCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGCMouseClicked
        // TODO add your handling code here:
        //afichage de l' Id
        Id = Integer.parseInt(model.getValueAt(jTableGC.getSelectedRow(), 0).toString());
      // JOptionPane.showMessageDialog(this, Id);
         
    }//GEN-LAST:event_jTableGCMouseClicked

    private void modifierButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierButton3ActionPerformed
        // TODO add your handling code here:
         
    // Vérifiez d'abord si un client est sélectionné dans la table
    if (Id != -1) {
        try {
            String nom = nomTxt.getText();
            String prenom = prénomTxt.getText();
            Date date = jDateTxt.getDate();
            Service service = (Service) listeService.getSelectedItem();

            // Créez un objet Client avec les nouvelles valeurs
            Client client = new Client(Id, nom, prenom, date, service);

            // Appelez la méthode "update" pour mettre à jour le client
            if (cs.update(client)) {
                JOptionPane.showMessageDialog(this, "Client modifié avec succès");
                load(); // Actualisez le tableau
                loadService();
            } else {
                JOptionPane.showMessageDialog(this, "Échec de la modification du client");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Sélectionnez un client à modifier dans la table");
    }

                
             

    }//GEN-LAST:event_modifierButton3ActionPerformed

    private void listeServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listeServiceActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton1;
    private com.toedter.calendar.JDateChooser jDateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableGC;
    private javax.swing.JComboBox listeService;
    private javax.swing.JButton modifierButton3;
    private javax.swing.JTextField nomTxt;
    private javax.swing.JTextField prénomTxt;
    private javax.swing.JButton supprimerButton2;
    // End of variables declaration//GEN-END:variables
}
